### ISSUE TITLE
Comment tags turn off syntax highlighting

### ISSUE THREAD

**Issue by tschofen** [raulriera/ColdFusion-Sugar#9]
Putting a CF comment around text disables all syntax highlighting after that line. Then the end of the CF comment tag has a red background behind the first two dashes. The same red box happens from then on for the beginning and end of every comment tag in that file.

```
                           ^
            red background around the first two dashes
```

**Comment by raulriera** [comment]
Yeah, for some reason it is getting mixed up with HTML comments...  I never found the fix for this besides doing FOUR dashes instead of three

**Comment by tschofen** [comment]
Works for me...thanks
